In [3]:
import pandas as pd
df = pd.read_csv('/root/timesnet/Time-Series-Library/data/stock_data.csv')
# print(df.head())
print(len(df))
new_df=df.drop(columns=['MA_10','MA_20','MA_50','成交额','振幅'])
#print(new_df.head())
#new_df.to_csv(path_or_buf='./data/new_stock_data.csv',index=False)
print(df)

1832
            date     开盘     收盘     最高     最低           成交额    振幅   MA_10  \
0     2017-05-12   8.68   8.90   8.90   8.64  8.091319e+08  2.99   8.769   
1     2017-05-15   8.89   8.86   8.95   8.81  4.764177e+08  1.57   8.756   
2     2017-05-16   8.84   8.84   8.85   8.73  4.610693e+08  1.35   8.746   
3     2017-05-17   8.81   8.77   8.81   8.75  3.659875e+08  0.68   8.732   
4     2017-05-18   8.72   8.73   8.77   8.71  1.987656e+08  0.68   8.731   
...          ...    ...    ...    ...    ...           ...   ...     ...   
1827  2024-11-19  11.75  11.68  11.96  11.55  2.849662e+09  3.49  11.634   
1828  2024-11-20  11.67  11.64  11.75  11.61  1.498818e+09  1.20  11.643   
1829  2024-11-21  11.62  11.59  11.65  11.56  1.023998e+09  0.77  11.611   
1830  2024-11-22  11.59  11.28  11.61  11.28  1.858072e+09  2.85  11.567   
1831  2024-11-25  11.28  11.18  11.34  11.14  1.310131e+09  1.77  11.525   

        MA_20    MA_50  Close_Lag1  Close_Lag2  
0      8.8805   9.1212        8.7

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
from datetime import datetime, timedelta

# 设置文件夹路径
folder_path = '/root/timesnet/Time-Series-Library/results/long_term_forecast_test_TimesNet_custom_ftMS_sl60_ll30_pl7_dm512_nh8_el2_dl1_df1024_expand2_dc4_fc1_ebtimeF_dtTrue_test_0'
metrics = np.load(os.path.join(folder_path, 'metrics.npy'))
preds = np.load(os.path.join(folder_path, 'pred.npy'))
trues = np.load(os.path.join(folder_path, 'true.npy'))

# 打印指标
mae, mse, rmse, mape, mspe = metrics
print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"MAPE: {mape}")
print(f"MSPE: {mspe}")
print(len(preds))


MAE: 0.3061193823814392
MSE: 0.19962744414806366
RMSE: 0.44679686427116394
MAPE: 0.028382234275341034
MSPE: 0.0016086101531982422
360


In [8]:
# 生成预测与真实值的对比图
time_steps = trues.shape[0]
start_time = datetime.now()
print(time_steps)
print(start_time)
freq = 'D'
time_index = pd.date_range(start=start_time, periods=time_steps, freq=freq)
preds_flat = preds[:, 0, 0]
trues_flat = trues[:, 0, 0]

# plt.figure(figsize=(10, 5))
# plt.plot(time_index, trues_flat, label='True', color='blue')
# plt.plot(time_index, preds_flat, label='Pred', color='red', linestyle='--')
# plt.xlabel('Time')
# plt.ylabel('Number')
# plt.title('True vs Pred')
# plt.legend()
# plt.grid(True)
# plt.tight_layout()
# plot_path = os.path.join(folder_path, 'prediction_vs_true.png')
# plt.savefig(plot_path)
# plt.close()


360
2024-12-04 21:46:13.131851


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os


# 设置文件夹路径
folder_path = '/root/timesnet/Time-Series-Library/results/long_term_forecast_test_TimeXer_custom_ftMS_sl60_ll30_pl7_dm512_nh8_el2_dl1_df2048_expand2_dc4_fc1_ebtimeF_dtTrue_test_0'
# 加载.npy文件
metrics = np.load(os.path.join(folder_path, 'metrics.npy'))
preds = np.load(os.path.join(folder_path, 'pred.npy'))
trues = np.load(os.path.join(folder_path, 'true.npy'))

print("preds:",preds)
print("trues:",trues)


# 2023-05-24 1468行 -1828行

preds: [[[12.352448]
  [12.35779 ]
  [12.389578]
  ...
  [12.326424]
  [12.276704]
  [12.303356]]

 [[12.280833]
  [12.28136 ]
  [12.325956]
  ...
  [12.313449]
  [12.273623]
  [12.293118]]

 [[12.202594]
  [12.248652]
  [12.313303]
  ...
  [12.352636]
  [12.321211]
  [12.354081]]

 ...

 [[12.038091]
  [12.086164]
  [12.023926]
  ...
  [11.986215]
  [11.987029]
  [12.001481]]

 [[11.826303]
  [11.872565]
  [11.889041]
  ...
  [11.767246]
  [11.677125]
  [11.781973]]

 [[11.614206]
  [11.647457]
  [11.577479]
  ...
  [11.531909]
  [11.500822]
  [11.661531]]]
trues: [[[12.01     ]
  [11.93     ]
  [12.1      ]
  ...
  [11.87     ]
  [11.6      ]
  [11.59     ]]

 [[11.93     ]
  [12.1      ]
  [11.9800005]
  ...
  [11.6      ]
  [11.59     ]
  [11.93     ]]

 [[12.1      ]
  [11.9800005]
  [11.87     ]
  ...
  [11.59     ]
  [11.93     ]
  [11.91     ]]

 ...

 [[11.610001 ]
  [11.54     ]
  [11.44     ]
  ...
  [11.68     ]
  [11.64     ]
  [11.59     ]]

 [[11.54     ]
  [11.44     ]


In [8]:
import numpy as np
import matplotlib.pyplot as plt
import os


# 设置文件夹路径
folder_path = '/root/timesnet/Time-Series-Library/results/long_term_forecast_test_TimesNet_custom_ftMS_sl60_ll30_pl7_dm512_nh8_el2_dl1_df1024_expand2_dc4_fc1_ebtimeF_dtTrue_test_0'
metrics = np.load(os.path.join(folder_path, 'metrics.npy'))
preds = np.load(os.path.join(folder_path, 'pred.npy'))
trues = np.load(os.path.join(folder_path, 'true.npy'))


mae, mse, rmse, mape, mspe = metrics
print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"MAPE: {mape}")
print(f"MSPE: {mspe}")
print(trues)



MAE: 0.3061193823814392
MSE: 0.19962744414806366
RMSE: 0.44679686427116394
MAPE: 0.028382234275341034
MSPE: 0.0016086101531982422
[[[12.01     ]
  [11.93     ]
  [12.1      ]
  ...
  [11.87     ]
  [11.6      ]
  [11.59     ]]

 [[11.93     ]
  [12.1      ]
  [11.9800005]
  ...
  [11.6      ]
  [11.59     ]
  [11.93     ]]

 [[12.1      ]
  [11.9800005]
  [11.87     ]
  ...
  [11.59     ]
  [11.93     ]
  [11.91     ]]

 ...

 [[11.610001 ]
  [11.54     ]
  [11.44     ]
  ...
  [11.68     ]
  [11.64     ]
  [11.59     ]]

 [[11.54     ]
  [11.44     ]
  [11.75     ]
  ...
  [11.64     ]
  [11.59     ]
  [11.28     ]]

 [[11.44     ]
  [11.75     ]
  [11.68     ]
  ...
  [11.59     ]
  [11.28     ]
  [11.18     ]]]


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# 1. Load the Dataset
data_path = '/root/timesnet/Time-Series-Library/data/new_stock_data.csv'
df = pd.read_csv(data_path, parse_dates=['date'])
df.set_index('date', inplace=True)
print(df.head())
print(f"Total number of rows in the dataset: {len(df)}")  # Should be 1832

# 2. Load and Aggregate Predictions
folder_path ='/root/timesnet/Time-Series-Library/test_results/long_term_forecast_test_TimesNet_custom_ftMS_sl60_ll30_pl7_dm512_nh8_el2_dl1_df1024_expand2_dc4_fc1_ebtimeF_dtTrue_test_0'
preds = np.load(os.path.join(folder_path, 'pred.npy'))  # Shape: (360, 7, 1)
trues = np.load(os.path.join(folder_path, 'true.npy'))  # Shape: (360,)
print(f"Predictions shape: {preds.shape}")  # Expected: (360, 7, 1)
print(f"True values shape: {trues.shape}")  # Expected: (360,)

# Aggregate predictions
aggregated_preds_last = preds[:, -1, 0]
aggregated_preds_avg = preds.mean(axis=1).squeeze()
print(f"Aggregated Predictions (Last) shape: {aggregated_preds_last.shape}")  # (360,)
print(f"Aggregated Predictions (Average) shape: {aggregated_preds_avg.shape}")  # (360,)

# Choose aggregation method
aggregated_preds = aggregated_preds_last  # or aggregated_preds_avg

# 3. Align Predictions with the Dataset
assert len(df) == 1832, "The dataset does not contain 1832 rows as expected."
assert aggregated_preds.shape[0] == 360, "The number of predictions does not match the test set size."

# Add 'Predictions' column initialized with NaN
df['Predictions'] = np.nan

# Define the test set's starting row index (0-based)
test_start_row = 1466  # Corresponds to row 1468

# Assign predictions to the 'Predictions' column for the test set
df.iloc[test_start_row:test_start_row + 360, df.columns.get_loc('Predictions')] = aggregated_preds

# Optional: Verify the assignment
print(df[['收盘', 'Predictions']].iloc[test_start_row:test_start_row + 5])

# 4. Visualize the Data with English Labels

# 4.1. Plotting the Entire Dataset
plt.style.use('seaborn-darkgrid')
plt.figure(figsize=(16, 8))
plt.plot(df.index, df['收盘'], label='True Close Price', color='blue')
plt.plot(df.index, df['Predictions'], label='Predicted Close Price', color='red', linestyle='--')
plt.axvline(df.index[test_start_row - 1], color='green', linestyle='--', label='End of Train Set')
plt.axvline(df.index[test_start_row + 366 - 1], color='orange', linestyle='--', label='End of Test Set')
plt.legend()
plt.title('Stock Close Price vs. Predictions')
plt.xlabel('Date')
plt.ylabel('Price')
plt.gcf().autofmt_xdate()
plt.grid(True)
plt.tight_layout()
plt.show()

# 4.2. Plotting the Test Set in Detail
test_start_date = df.index[test_start_row]
test_end_date = df.index[test_start_row + 366 - 1]
mask = (df.index >= test_start_date) & (df.index <= test_end_date)
plt.figure(figsize=(16, 8))
plt.plot(df.loc[mask].index, df.loc[mask, '收盘'], label='True Close Price', color='blue')
plt.plot(df.loc[mask].index, df.loc[mask, 'Predictions'], label='Predicted Close Price', color='red', linestyle='--')
plt.legend()
plt.title('Test Set: Stock Close Price vs. Predictions')
plt.xlabel('Date')
plt.ylabel('Price')
plt.gcf().autofmt_xdate()
plt.grid(True)
plt.tight_layout()
plt.show()

              开盘    收盘    最高    最低          成交额    振幅  MA_10   MA_20   MA_50  \
date                                                                           
2017-05-12  8.68  8.90  8.90  8.64  809131904.0  2.99  8.769  8.8805  9.1212   
2017-05-15  8.89  8.86  8.95  8.81  476417664.0  1.57  8.756  8.8695  9.1086   
2017-05-16  8.84  8.84  8.85  8.73  461069296.0  1.35  8.746  8.8565  9.0968   
2017-05-17  8.81  8.77  8.81  8.75  365987536.0  0.68  8.732  8.8425  9.0842   
2017-05-18  8.72  8.73  8.77  8.71  198765579.0  0.68  8.731  8.8335  9.0698   

            Close_Lag1  Close_Lag2  
date                                
2017-05-12        8.70        8.67  
2017-05-15        8.90        8.70  
2017-05-16        8.86        8.90  
2017-05-17        8.84        8.86  
2017-05-18        8.77        8.84  
Total number of rows in the dataset: 1832
Predictions shape: (67, 7, 1)
True values shape: (67, 7, 1)
Aggregated Predictions (Last) shape: (67,)
Aggregated Predictions (Average) sh

AssertionError: The number of predictions does not match the test set size.

In [6]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 持久模型预测（使用上一期的收盘价作为预测）
persistent_preds = df['收盘'].shift(1).iloc[test_start_row:test_start_row + 360].values

aggregated_trues = trues[:,-1,0]
# 计算持久模型的指标
persistent_mae = mean_absolute_error(aggregated_trues, persistent_preds)
persistent_mse = mean_squared_error(aggregated_trues, persistent_preds)
persistent_rmse = np.sqrt(persistent_mse)
persistent_mape = np.mean(np.abs((aggregated_trues - persistent_preds) / trues)) * 100
persistent_mspe = np.mean(((aggregated_trues - persistent_preds) / trues) ** 2)

print(f"Persistent Model MAE: {persistent_mae}")
print(f"Persistent Model MSE: {persistent_mse}")
print(f"Persistent Model RMSE: {persistent_rmse}")
print(f"Persistent Model MAPE: {persistent_mape}%")
print(f"Persistent Model MSPE: {persistent_mspe}")

Persistent Model MAE: 0.3131666560702854
Persistent Model MSE: 0.20821221323660477
Persistent Model RMSE: 0.4563027648794217
Persistent Model MAPE: 2.953982833531167%
Persistent Model MSPE: 0.0018641340449065114
